### PR TITLE
Allow React ^16 as a peer

### PR DESCRIPTION
**Pull request by damiangreen**
Allow React ^16 as a peer

### CODE REVIEW

**Comment by anthony0030** [comment]
+1
(I was about to make the same pull request.)

**Comment by damiangreen** [comment]
Will you be publishing to npm @anthony0030 ?

**Comment by anthony0030** [comment]
I am in contact with the owner of this repo. there a few bugs that I am trying to fix.
When it is ready I will ask Mr. Pavlo to publish it. It will be ready next week.

**Comment by anthony0030** [comment]
Yes, it will be published
I am in direct contact with the owner of this repo.
I will help maintain it.
There are a few problems that I would like to fix.
I aim to have it fixed in the new week.

**Pull request merged**
